// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightstep_carrier.proto

#include "lightstep_carrier.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace lightstep {
class BinaryCarrierDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BinaryCarrier>
      _instance;
} _BinaryCarrier_default_instance_;
class BasicTracerCarrier_BaggageItemsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BasicTracerCarrier_BaggageItemsEntry_DoNotUse>
      _instance;
} _BasicTracerCarrier_BaggageItemsEntry_DoNotUse_default_instance_;
class BasicTracerCarrierDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BasicTracerCarrier>
      _instance;
} _BasicTracerCarrier_default_instance_;
class TextCarrierPairDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TextCarrierPair>
      _instance;
} _TextCarrierPair_default_instance_;
}  // namespace lightstep
namespace protobuf_lightstep_5fcarrier_2eproto {
void InitDefaultsBinaryCarrierImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_lightstep_5fcarrier_2eproto::InitDefaultsTextCarrierPair();
  protobuf_lightstep_5fcarrier_2eproto::InitDefaultsBasicTracerCarrier();
  {
    void* ptr = &::lightstep::_BinaryCarrier_default_instance_;
    new (ptr) ::lightstep::BinaryCarrier();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::lightstep::BinaryCarrier::InitAsDefaultInstance();
}

void InitDefaultsBinaryCarrier() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsBinaryCarrierImpl);
}

void InitDefaultsBasicTracerCarrier_BaggageItemsEntry_DoNotUseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::lightstep::_BasicTracerCarrier_BaggageItemsEntry_DoNotUse_default_instance_;
    new (ptr) ::lightstep::BasicTracerCarrier_BaggageItemsEntry_DoNotUse();
  }
  ::lightstep::BasicTracerCarrier_BaggageItemsEntry_DoNotUse::InitAsDefaultInstance();
}

void InitDefaultsBasicTracerCarrier_BaggageItemsEntry_DoNotUse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsBasicTracerCarrier_BaggageItemsEntry_DoNotUseImpl);
}

void InitDefaultsBasicTracerCarrierImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_lightstep_5fcarrier_2eproto::InitDefaultsBasicTracerCarrier_BaggageItemsEntry_DoNotUse();
  {
    void* ptr = &::lightstep::_BasicTracerCarrier_default_instance_;
    new (ptr) ::lightstep::BasicTracerCarrier();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::lightstep::BasicTracerCarrier::InitAsDefaultInstance();
}

void InitDefaultsBasicTracerCarrier() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsBasicTracerCarrierImpl);
}

void InitDefaultsTextCarrierPairImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::lightstep::_TextCarrierPair_default_instance_;
    new (ptr) ::lightstep::TextCarrierPair();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::lightstep::TextCarrierPair::InitAsDefaultInstance();
}

void InitDefaultsTextCarrierPair() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTextCarrierPairImpl);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BinaryCarrier, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BinaryCarrier, text_ctx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BinaryCarrier, basic_ctx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BasicTracerCarrier_BaggageItemsEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BasicTracerCarrier_BaggageItemsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BasicTracerCarrier_BaggageItemsEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BasicTracerCarrier_BaggageItemsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BasicTracerCarrier, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BasicTracerCarrier, trace_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BasicTracerCarrier, span_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BasicTracerCarrier, sampled_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::BasicTracerCarrier, baggage_items_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::TextCarrierPair, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::TextCarrierPair, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::lightstep::TextCarrierPair, value_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::lightstep::BinaryCarrier)},
  { 7, 14, sizeof(::lightstep::BasicTracerCarrier_BaggageItemsEntry_DoNotUse)},
  { 16, -1, sizeof(::lightstep::BasicTracerCarrier)},
  { 25, -1, sizeof(::lightstep::TextCarrierPair)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::lightstep::_BinaryCarrier_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::lightstep::_BasicTracerCarrier_BaggageItemsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::lightstep::_BasicTracerCarrier_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::lightstep::_TextCarrierPair_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "lightstep_carrier.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\027lightstep_carrier.proto\022\tlightstep\"o\n\r"
      "BinaryCarrier\022,\n\010text_ctx\030\001 \003(\0132\032.lights"
      "tep.TextCarrierPair\0220\n\tbasic_ctx\030\002 \001(\0132\035"
      ".lightstep.BasicTracerCarrier\"\305\001\n\022BasicT"
      "racerCarrier\022\020\n\010trace_id\030\001 \001(\006\022\017\n\007span_i"
      "d\030\002 \001(\006\022\017\n\007sampled\030\003 \001(\010\022F\n\rbaggage_item"
      "s\030\004 \003(\0132/.lightstep.BasicTracerCarrier.B"
      "aggageItemsEntry\0323\n\021BaggageItemsEntry\022\013\n"
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"-\n\017TextCar"
      "rierPair\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\tb\006pr"
      "oto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 404);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lightstep_carrier.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_lightstep_5fcarrier_2eproto
namespace lightstep {

// ===================================================================

void BinaryCarrier::InitAsDefaultInstance() {
  ::lightstep::_BinaryCarrier_default_instance_._instance.get_mutable()->basic_ctx_ = const_cast< ::lightstep::BasicTracerCarrier*>(
      ::lightstep::BasicTracerCarrier::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BinaryCarrier::kTextCtxFieldNumber;
const int BinaryCarrier::kBasicCtxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BinaryCarrier::BinaryCarrier()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_lightstep_5fcarrier_2eproto::InitDefaultsBinaryCarrier();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:lightstep.BinaryCarrier)
}
BinaryCarrier::BinaryCarrier(const BinaryCarrier& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      text_ctx_(from.text_ctx_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_basic_ctx()) {
    basic_ctx_ = new ::lightstep::BasicTracerCarrier(*from.basic_ctx_);
  } else {
    basic_ctx_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:lightstep.BinaryCarrier)
}

void BinaryCarrier::SharedCtor() {
  basic_ctx_ = NULL;
  _cached_size_ = 0;
}

BinaryCarrier::~BinaryCarrier() {
  // @@protoc_insertion_point(destructor:lightstep.BinaryCarrier)
  SharedDtor();
}

void BinaryCarrier::SharedDtor() {
  if (this != internal_default_instance()) delete basic_ctx_;
}

void BinaryCarrier::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BinaryCarrier::descriptor() {
  ::protobuf_lightstep_5fcarrier_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_lightstep_5fcarrier_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BinaryCarrier& BinaryCarrier::default_instance() {
  ::protobuf_lightstep_5fcarrier_2eproto::InitDefaultsBinaryCarrier();
  return *internal_default_instance();
}

BinaryCarrier* BinaryCarrier::New(::google::protobuf::Arena* arena) const {
  BinaryCarrier* n = new BinaryCarrier;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BinaryCarrier::Clear() {
// @@protoc_insertion_point(message_clear_start:lightstep.BinaryCarrier)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  text_ctx_.Clear();
  if (GetArenaNoVirtual() == NULL && basic_ctx_ != NULL) {
    delete basic_ctx_;
  }
  basic_ctx_ = NULL;
  _internal_metadata_.Clear();
}

bool BinaryCarrier::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:lightstep.BinaryCarrier)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .lightstep.TextCarrierPair text_ctx = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_text_ctx()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .lightstep.BasicTracerCarrier basic_ctx = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_basic_ctx()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:lightstep.BinaryCarrier)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:lightstep.BinaryCarrier)
  return false;
#undef DO_
}

void BinaryCarrier::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:lightstep.BinaryCarrier)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .lightstep.TextCarrierPair text_ctx = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->text_ctx_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->text_ctx(static_cast<int>(i)), output);
  }

  // .lightstep.BasicTracerCarrier basic_ctx = 2;
  if (this->has_basic_ctx()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->basic_ctx_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:lightstep.BinaryCarrier)
}

::google::protobuf::uint8* BinaryCarrier::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:lightstep.BinaryCarrier)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .lightstep.TextCarrierPair text_ctx = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->text_ctx_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->text_ctx(static_cast<int>(i)), deterministic, target);
  }

  // .lightstep.BasicTracerCarrier basic_ctx = 2;
  if (this->has_basic_ctx()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->basic_ctx_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lightstep.BinaryCarrier)
  return target;
}

size_t BinaryCarrier::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lightstep.BinaryCarrier)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .lightstep.TextCarrierPair text_ctx = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->text_ctx_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->text_ctx(static_cast<int>(i)));
    }
  }

  // .lightstep.BasicTracerCarrier basic_ctx = 2;
  if (this->has_basic_ctx()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->basic_ctx_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BinaryCarrier::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:lightstep.BinaryCarrier)
  GOOGLE_DCHECK_NE(&from, this);
  const BinaryCarrier* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BinaryCarrier>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:lightstep.BinaryCarrier)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:lightstep.BinaryCarrier)
    MergeFrom(*source);
  }
}

void BinaryCarrier::MergeFrom(const BinaryCarrier& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:lightstep.BinaryCarrier)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  text_ctx_.MergeFrom(from.text_ctx_);
  if (from.has_basic_ctx()) {
    mutable_basic_ctx()->::lightstep::BasicTracerCarrier::MergeFrom(from.basic_ctx());
  }
}

void BinaryCarrier::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:lightstep.BinaryCarrier)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BinaryCarrier::CopyFrom(const BinaryCarrier& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lightstep.BinaryCarrier)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BinaryCarrier::IsInitialized() const {
  return true;
}

void BinaryCarrier::Swap(BinaryCarrier* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BinaryCarrier::InternalSwap(BinaryCarrier* other) {
  using std::swap;
  text_ctx_.InternalSwap(&other->text_ctx_);
  swap(basic_ctx_, other->basic_ctx_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BinaryCarrier::GetMetadata() const {
  protobuf_lightstep_5fcarrier_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_lightstep_5fcarrier_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

BasicTracerCarrier_BaggageItemsEntry_DoNotUse::BasicTracerCarrier_BaggageItemsEntry_DoNotUse() {}
BasicTracerCarrier_BaggageItemsEntry_DoNotUse::BasicTracerCarrier_BaggageItemsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void BasicTracerCarrier_BaggageItemsEntry_DoNotUse::MergeFrom(const BasicTracerCarrier_BaggageItemsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata BasicTracerCarrier_BaggageItemsEntry_DoNotUse::GetMetadata() const {
  ::protobuf_lightstep_5fcarrier_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_lightstep_5fcarrier_2eproto::file_level_metadata[1];
}
void BasicTracerCarrier_BaggageItemsEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void BasicTracerCarrier::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BasicTracerCarrier::kTraceIdFieldNumber;
const int BasicTracerCarrier::kSpanIdFieldNumber;
const int BasicTracerCarrier::kSampledFieldNumber;
const int BasicTracerCarrier::kBaggageItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BasicTracerCarrier::BasicTracerCarrier()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_lightstep_5fcarrier_2eproto::InitDefaultsBasicTracerCarrier();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:lightstep.BasicTracerCarrier)
}
BasicTracerCarrier::BasicTracerCarrier(const BasicTracerCarrier& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  baggage_items_.MergeFrom(from.baggage_items_);
  ::memcpy(&trace_id_, &from.trace_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&sampled_) -
    reinterpret_cast<char*>(&trace_id_)) + sizeof(sampled_));
  // @@protoc_insertion_point(copy_constructor:lightstep.BasicTracerCarrier)
}

void BasicTracerCarrier::SharedCtor() {
  ::memset(&trace_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sampled_) -
      reinterpret_cast<char*>(&trace_id_)) + sizeof(sampled_));
  _cached_size_ = 0;
}

BasicTracerCarrier::~BasicTracerCarrier() {
  // @@protoc_insertion_point(destructor:lightstep.BasicTracerCarrier)
  SharedDtor();
}

void BasicTracerCarrier::SharedDtor() {
}

void BasicTracerCarrier::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BasicTracerCarrier::descriptor() {
  ::protobuf_lightstep_5fcarrier_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_lightstep_5fcarrier_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BasicTracerCarrier& BasicTracerCarrier::default_instance() {
  ::protobuf_lightstep_5fcarrier_2eproto::InitDefaultsBasicTracerCarrier();
  return *internal_default_instance();
}

BasicTracerCarrier* BasicTracerCarrier::New(::google::protobuf::Arena* arena) const {
  BasicTracerCarrier* n = new BasicTracerCarrier;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BasicTracerCarrier::Clear() {
// @@protoc_insertion_point(message_clear_start:lightstep.BasicTracerCarrier)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  baggage_items_.Clear();
  ::memset(&trace_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sampled_) -
      reinterpret_cast<char*>(&trace_id_)) + sizeof(sampled_));
  _internal_metadata_.Clear();
}

bool BasicTracerCarrier::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:lightstep.BasicTracerCarrier)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // fixed64 trace_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &trace_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // fixed64 span_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &span_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool sampled = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &sampled_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> baggage_items = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          BasicTracerCarrier_BaggageItemsEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              BasicTracerCarrier_BaggageItemsEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&baggage_items_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "lightstep.BasicTracerCarrier.BaggageItemsEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "lightstep.BasicTracerCarrier.BaggageItemsEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:lightstep.BasicTracerCarrier)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:lightstep.BasicTracerCarrier)
  return false;
#undef DO_
}

void BasicTracerCarrier::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:lightstep.BasicTracerCarrier)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // fixed64 trace_id = 1;
  if (this->trace_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(1, this->trace_id(), output);
  }

  // fixed64 span_id = 2;
  if (this->span_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(2, this->span_id(), output);
  }

  // bool sampled = 3;
  if (this->sampled() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->sampled(), output);
  }

  // map<string, string> baggage_items = 4;
  if (!this->baggage_items().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "lightstep.BasicTracerCarrier.BaggageItemsEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "lightstep.BasicTracerCarrier.BaggageItemsEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->baggage_items().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->baggage_items().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->baggage_items().begin();
          it != this->baggage_items().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<BasicTracerCarrier_BaggageItemsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(baggage_items_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            4, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<BasicTracerCarrier_BaggageItemsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->baggage_items().begin();
          it != this->baggage_items().end(); ++it) {
        entry.reset(baggage_items_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            4, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:lightstep.BasicTracerCarrier)
}

::google::protobuf::uint8* BasicTracerCarrier::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:lightstep.BasicTracerCarrier)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // fixed64 trace_id = 1;
  if (this->trace_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(1, this->trace_id(), target);
  }

  // fixed64 span_id = 2;
  if (this->span_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(2, this->span_id(), target);
  }

  // bool sampled = 3;
  if (this->sampled() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->sampled(), target);
  }

  // map<string, string> baggage_items = 4;
  if (!this->baggage_items().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "lightstep.BasicTracerCarrier.BaggageItemsEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "lightstep.BasicTracerCarrier.BaggageItemsEntry.value");
      }
    };

    if (deterministic &&
        this->baggage_items().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->baggage_items().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->baggage_items().begin();
          it != this->baggage_items().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<BasicTracerCarrier_BaggageItemsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(baggage_items_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       4, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<BasicTracerCarrier_BaggageItemsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->baggage_items().begin();
          it != this->baggage_items().end(); ++it) {
        entry.reset(baggage_items_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       4, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lightstep.BasicTracerCarrier)
  return target;
}

size_t BasicTracerCarrier::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lightstep.BasicTracerCarrier)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, string> baggage_items = 4;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->baggage_items_size());
  {
    ::google::protobuf::scoped_ptr<BasicTracerCarrier_BaggageItemsEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->baggage_items().begin();
        it != this->baggage_items().end(); ++it) {
      entry.reset(baggage_items_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // fixed64 trace_id = 1;
  if (this->trace_id() != 0) {
    total_size += 1 + 8;
  }

  // fixed64 span_id = 2;
  if (this->span_id() != 0) {
    total_size += 1 + 8;
  }

  // bool sampled = 3;
  if (this->sampled() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BasicTracerCarrier::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:lightstep.BasicTracerCarrier)
  GOOGLE_DCHECK_NE(&from, this);
  const BasicTracerCarrier* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BasicTracerCarrier>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:lightstep.BasicTracerCarrier)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:lightstep.BasicTracerCarrier)
    MergeFrom(*source);
  }
}

void BasicTracerCarrier::MergeFrom(const BasicTracerCarrier& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:lightstep.BasicTracerCarrier)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  baggage_items_.MergeFrom(from.baggage_items_);
  if (from.trace_id() != 0) {
    set_trace_id(from.trace_id());
  }
  if (from.span_id() != 0) {
    set_span_id(from.span_id());
  }
  if (from.sampled() != 0) {
    set_sampled(from.sampled());
  }
}

void BasicTracerCarrier::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:lightstep.BasicTracerCarrier)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BasicTracerCarrier::CopyFrom(const BasicTracerCarrier& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lightstep.BasicTracerCarrier)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicTracerCarrier::IsInitialized() const {
  return true;
}

void BasicTracerCarrier::Swap(BasicTracerCarrier* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BasicTracerCarrier::InternalSwap(BasicTracerCarrier* other) {
  using std::swap;
  baggage_items_.Swap(&other->baggage_items_);
  swap(trace_id_, other->trace_id_);
  swap(span_id_, other->span_id_);
  swap(sampled_, other->sampled_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BasicTracerCarrier::GetMetadata() const {
  protobuf_lightstep_5fcarrier_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_lightstep_5fcarrier_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void TextCarrierPair::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TextCarrierPair::kKeyFieldNumber;
const int TextCarrierPair::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TextCarrierPair::TextCarrierPair()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_lightstep_5fcarrier_2eproto::InitDefaultsTextCarrierPair();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:lightstep.TextCarrierPair)
}
TextCarrierPair::TextCarrierPair(const TextCarrierPair& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:lightstep.TextCarrierPair)
}

void TextCarrierPair::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

TextCarrierPair::~TextCarrierPair() {
  // @@protoc_insertion_point(destructor:lightstep.TextCarrierPair)
  SharedDtor();
}

void TextCarrierPair::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void TextCarrierPair::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TextCarrierPair::descriptor() {
  ::protobuf_lightstep_5fcarrier_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_lightstep_5fcarrier_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TextCarrierPair& TextCarrierPair::default_instance() {
  ::protobuf_lightstep_5fcarrier_2eproto::InitDefaultsTextCarrierPair();
  return *internal_default_instance();
}

TextCarrierPair* TextCarrierPair::New(::google::protobuf::Arena* arena) const {
  TextCarrierPair* n = new TextCarrierPair;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TextCarrierPair::Clear() {
// @@protoc_insertion_point(message_clear_start:lightstep.TextCarrierPair)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool TextCarrierPair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:lightstep.TextCarrierPair)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "lightstep.TextCarrierPair.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), static_cast<int>(this->value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "lightstep.TextCarrierPair.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:lightstep.TextCarrierPair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:lightstep.TextCarrierPair)
  return false;
#undef DO_
}

void TextCarrierPair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:lightstep.TextCarrierPair)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lightstep.TextCarrierPair.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lightstep.TextCarrierPair.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:lightstep.TextCarrierPair)
}

::google::protobuf::uint8* TextCarrierPair::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:lightstep.TextCarrierPair)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lightstep.TextCarrierPair.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "lightstep.TextCarrierPair.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lightstep.TextCarrierPair)
  return target;
}

size_t TextCarrierPair::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lightstep.TextCarrierPair)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TextCarrierPair::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:lightstep.TextCarrierPair)
  GOOGLE_DCHECK_NE(&from, this);
  const TextCarrierPair* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TextCarrierPair>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:lightstep.TextCarrierPair)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:lightstep.TextCarrierPair)
    MergeFrom(*source);
  }
}

void TextCarrierPair::MergeFrom(const TextCarrierPair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:lightstep.TextCarrierPair)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void TextCarrierPair::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:lightstep.TextCarrierPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TextCarrierPair::CopyFrom(const TextCarrierPair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lightstep.TextCarrierPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TextCarrierPair::IsInitialized() const {
  return true;
}

void TextCarrierPair::Swap(TextCarrierPair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TextCarrierPair::InternalSwap(TextCarrierPair* other) {
  using std::swap;
  key_.Swap(&other->key_);
  value_.Swap(&other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TextCarrierPair::GetMetadata() const {
  protobuf_lightstep_5fcarrier_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_lightstep_5fcarrier_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace lightstep

// @@protoc_insertion_point(global_scope)
